-- SDOC persistent case workflow.
-- Apply in Supabase SQL Editor or through the Supabase CLI before setting
-- SDOC_STORE=supabase. No anon/authenticated policies are created: access is
-- server-side through the secret service key only.

create table if not exists public.shipment_cases (
  case_id text primary key,
  shipment_reference text not null unique,
  state text not null check (state in ('VERIFIED','DISCREPANCY','NEEDS_REVIEW','WAITING','BLOCKED')),
  state_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  waiting_since timestamptz
);

create table if not exists public.routed_messages (
  email_id text primary key,
  sender text,
  subject text,
  category text not null,
  payload_json jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.case_emails (
  email_id text primary key,
  case_id text not null references public.shipment_cases(case_id) on delete cascade,
  sender text,
  subject text,
  received_at text,
  category text not null,
  evaluator_status text not null,
  payload_json jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  document_id bigint generated by default as identity primary key,
  case_id text not null references public.shipment_cases(case_id) on delete cascade,
  role text not null,
  created_at timestamptz not null default now(),
  unique(case_id, role)
);

create table if not exists public.document_versions (
  version_id bigint generated by default as identity primary key,
  document_id bigint not null references public.documents(document_id) on delete cascade,
  email_id text not null references public.case_emails(email_id) on delete cascade,
  source_path text not null,
  version_index integer not null,
  version_label text,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  unique(document_id, source_path)
);

create table if not exists public.comparisons (
  comparison_id bigint generated by default as identity primary key,
  case_id text not null references public.shipment_cases(case_id) on delete cascade,
  email_id text not null references public.case_emails(email_id) on delete cascade unique,
  state text not null,
  defect_fields jsonb not null default '[]'::jsonb,
  evidence_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.review_tasks (
  task_id bigint generated by default as identity primary key,
  case_id text not null references public.shipment_cases(case_id) on delete cascade,
  kind text not null,
  reason text,
  status text not null default 'OPEN' check (status in ('OPEN','RESOLVED','CANCELLED')),
  assignee text,
  resolution_note text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create unique index if not exists one_open_sdoc_task_per_case
  on public.review_tasks(case_id) where status = 'OPEN';

create table if not exists public.audit_events (
  event_id bigint generated by default as identity primary key,
  case_id text not null references public.shipment_cases(case_id) on delete cascade,
  event_type text not null,
  actor text not null,
  detail_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.ingest_sdoc_result(
  p_email jsonb,
  p_record jsonb,
  p_evidence jsonb,
  p_reference text,
  p_case_id text,
  p_state text,
  p_documents jsonb,
  p_now double precision
) returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := to_timestamp(p_now);
  v_email_id text := coalesce(p_email->>'email_id', p_email->>'id');
  v_previous_state text;
  v_previous_reason text;
  v_inserted integer;
  v_doc jsonb;
  v_document_id bigint;
  v_version_index integer;
  v_active_version integer;
  v_task_id bigint;
begin
  if p_record->>'category' <> 'BL_COMPARISON' then
    insert into routed_messages(email_id,sender,subject,category,payload_json,created_at)
    values(v_email_id,p_email->>'from',p_email->>'subject',p_record->>'category',p_email,v_now)
    on conflict(email_id) do nothing;
    return null;
  end if;

  insert into shipment_cases(case_id,shipment_reference,state,state_reason,created_at,updated_at,waiting_since)
  values(p_case_id,p_reference,'WAITING','awaiting_processing',v_now,v_now,v_now)
  on conflict(shipment_reference) do nothing;

  select state,state_reason into v_previous_state,v_previous_reason
    from shipment_cases where case_id=p_case_id for update;

  insert into case_emails(email_id,case_id,sender,subject,received_at,category,evaluator_status,payload_json,created_at)
  values(v_email_id,p_case_id,p_email->>'from',p_email->>'subject',
         coalesce(p_email->>'received_at',p_email->>'date'),p_record->>'category',
         p_record->>'status',p_email,v_now)
  on conflict(email_id) do nothing;
  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then
    return p_case_id;
  end if;

  insert into audit_events(case_id,event_type,actor,detail_json,created_at)
  values(p_case_id,'EMAIL_INGESTED','system',
         jsonb_build_object('email_id',v_email_id,'category',p_record->>'category'),v_now);

  for v_doc in select value from jsonb_array_elements(coalesce(p_documents,'[]'::jsonb)) loop
    insert into documents(case_id,role,created_at)
    values(p_case_id,coalesce(v_doc->>'role','UNKNOWN'),v_now)
    on conflict(case_id,role) do update set role=excluded.role
    returning document_id into v_document_id;

    if v_doc->>'version_index' is null then
      select coalesce(max(version_index),0)+1 into v_version_index
        from document_versions where document_id=v_document_id;
    else
      v_version_index := (v_doc->>'version_index')::integer;
    end if;

    insert into document_versions(document_id,email_id,source_path,version_index,version_label,is_active,created_at)
    values(v_document_id,v_email_id,v_doc->>'source_path',v_version_index,v_doc->>'version_label',false,v_now)
    on conflict(document_id,source_path) do nothing;
    get diagnostics v_inserted = row_count;

    if v_inserted > 0 then
      select coalesce(max(version_index),0) into v_active_version
        from document_versions where document_id=v_document_id and is_active;
      if v_version_index >= v_active_version then
        update document_versions set is_active=false where document_id=v_document_id;
        update document_versions set is_active=true
          where document_id=v_document_id and source_path=v_doc->>'source_path';
      end if;
      insert into audit_events(case_id,event_type,actor,detail_json,created_at)
      values(p_case_id,'DOCUMENT_VERSION_ADDED','system',
             jsonb_build_object('role',v_doc->>'role','source_path',v_doc->>'source_path',
                                'version_index',v_version_index),v_now);
    end if;
  end loop;

  insert into comparisons(case_id,email_id,state,defect_fields,evidence_json,created_at)
  values(p_case_id,v_email_id,p_state,coalesce(p_record->'defect_fields','[]'::jsonb),p_evidence,v_now)
  on conflict(email_id) do nothing;

  update shipment_cases set
    state=p_state,
    state_reason=p_record->>'review_reason',
    updated_at=v_now,
    waiting_since=case
      when p_state='WAITING' and v_previous_state='WAITING' then coalesce(waiting_since,v_now)
      when p_state='WAITING' then v_now
      else null
    end
  where case_id=p_case_id;

  if v_previous_state is distinct from p_state
     or v_previous_reason is distinct from p_record->>'review_reason' then
    insert into audit_events(case_id,event_type,actor,detail_json,created_at)
    values(p_case_id,'STATE_CHANGED','system',
           jsonb_build_object('from',v_previous_state,'to',p_state,
                              'reason',p_record->>'review_reason'),v_now);
  end if;

  select task_id into v_task_id from review_tasks
    where case_id=p_case_id and status='OPEN' limit 1;
  if p_state in ('DISCREPANCY','NEEDS_REVIEW','BLOCKED') then
    if v_task_id is null then
      insert into review_tasks(case_id,kind,reason,created_at)
      values(p_case_id,p_state,p_record->>'review_reason',v_now);
      insert into audit_events(case_id,event_type,actor,detail_json,created_at)
      values(p_case_id,'REVIEW_TASK_CREATED','system',
             jsonb_build_object('kind',p_state,'reason',p_record->>'review_reason'),v_now);
    else
      update review_tasks set kind=p_state,reason=p_record->>'review_reason'
        where task_id=v_task_id;
    end if;
  elsif v_task_id is not null then
    update review_tasks set status='CANCELLED',resolved_at=v_now,
      resolution_note='Superseded by a new automated result'
      where task_id=v_task_id;
  end if;
  return p_case_id;
end;
$$;

create or replace function public.mark_sdoc_cases_overdue(
  p_wait_seconds integer,
  p_now double precision
) returns text[]
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := to_timestamp(p_now);
  v_case record;
  v_ids text[] := array[]::text[];
begin
  for v_case in
    select case_id from shipment_cases
    where state='WAITING' and waiting_since <= v_now - make_interval(secs => p_wait_seconds)
    for update
  loop
    update shipment_cases set state='BLOCKED',state_reason='missing_document_timeout',
      updated_at=v_now,waiting_since=null where case_id=v_case.case_id;
    insert into review_tasks(case_id,kind,reason,created_at)
    values(v_case.case_id,'BLOCKED','missing_document_timeout',v_now)
    on conflict do nothing;
    insert into audit_events(case_id,event_type,actor,detail_json,created_at)
    values(v_case.case_id,'STATE_CHANGED','system',
           jsonb_build_object('from','WAITING','to','BLOCKED','reason','missing_document_timeout'),v_now);
    v_ids := array_append(v_ids,v_case.case_id);
  end loop;
  return v_ids;
end;
$$;

create or replace function public.resolve_sdoc_review_task(
  p_task_id bigint,
  p_actor text,
  p_note text,
  p_now double precision
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_case_id text;
begin
  update review_tasks set status='RESOLVED',assignee=p_actor,
    resolution_note=p_note,resolved_at=to_timestamp(p_now)
    where task_id=p_task_id and status='OPEN'
    returning case_id into v_case_id;
  if v_case_id is null then
    raise exception 'open review task not found';
  end if;
  insert into audit_events(case_id,event_type,actor,detail_json,created_at)
  values(v_case_id,'REVIEW_TASK_RESOLVED',p_actor,
         jsonb_build_object('task_id',p_task_id,'note',p_note),to_timestamp(p_now));
end;
$$;

alter table public.shipment_cases enable row level security;
alter table public.routed_messages enable row level security;
alter table public.case_emails enable row level security;
alter table public.documents enable row level security;
alter table public.document_versions enable row level security;
alter table public.comparisons enable row level security;
alter table public.review_tasks enable row level security;
alter table public.audit_events enable row level security;

revoke all on function public.ingest_sdoc_result(jsonb,jsonb,jsonb,text,text,text,jsonb,double precision)
  from public, anon, authenticated;
revoke all on function public.mark_sdoc_cases_overdue(integer,double precision)
  from public, anon, authenticated;
revoke all on function public.resolve_sdoc_review_task(bigint,text,text,double precision)
  from public, anon, authenticated;
grant execute on function public.ingest_sdoc_result(jsonb,jsonb,jsonb,text,text,text,jsonb,double precision)
  to service_role;
grant execute on function public.mark_sdoc_cases_overdue(integer,double precision)
  to service_role;
grant execute on function public.resolve_sdoc_review_task(bigint,text,text,double precision)
  to service_role;
